$ErrorActionPreference = "Stop"

function Escape-TomlString([string]$Value) {
    return $Value.Replace("\", "\\").Replace('"', '\"')
}

$RepoRoot = (Get-Location).Path
$CodexDir = Join-Path $RepoRoot ".codex"
$ConfigPath = Join-Path $CodexDir "config.toml"

New-Item -ItemType Directory -Force -Path $CodexDir | Out-Null

$ProjectId = Read-Host "Enter the Overleaf Project ID"
if ([string]::IsNullOrWhiteSpace($ProjectId)) {
    throw "Project ID cannot be empty."
}

$SecureToken = Read-Host "Enter the Overleaf Git token (hidden)" -AsSecureString
$BSTR = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($SecureToken)

try {
    $PlainToken = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($BSTR)
}
finally {
    [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($BSTR)
}

if ([string]::IsNullOrWhiteSpace($PlainToken)) {
    throw "Token cannot be empty."
}

$TokenDir = Join-Path $env:APPDATA "overleaf-mcp\tokens"
New-Item -ItemType Directory -Force -Path $TokenDir | Out-Null

$SafeRepoName = Split-Path $RepoRoot -Leaf
$SafeRepoName = ($SafeRepoName -replace '[^A-Za-z0-9._-]', '_')
$TokenPath = Join-Path $TokenDir "$SafeRepoName-token.txt"

Set-Content -Path $TokenPath -Value $PlainToken -NoNewline -Encoding UTF8
$PlainToken = $null

# Restrict the token file to the current user where possible.
try {
    $CurrentUser = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
    $Acl = New-Object System.Security.AccessControl.FileSecurity
    $Rule = New-Object System.Security.AccessControl.FileSystemAccessRule(
        $CurrentUser,
        "FullControl",
        "Allow"
    )
    $Acl.SetOwner([System.Security.Principal.NTAccount]$CurrentUser)
    $Acl.SetAccessRuleProtection($true, $false)
    $Acl.AddAccessRule($Rule)
    Set-Acl -Path $TokenPath -AclObject $Acl
}
catch {
    Write-Warning "Could not tighten file ACL automatically. Protect this token file manually: $TokenPath"
}

$EscapedProjectId = Escape-TomlString $ProjectId
$EscapedTokenPath = Escape-TomlString $TokenPath

$Config = @"
# Generated by configure-overleaf-mcp.ps1
# Contains no Git token. The token is stored outside the repository.

[mcp_servers.overleaf]
command = "cmd"
args = ["/c", "npx", "-y", "@mjyoo2/overleaf-mcp"]
default_tools_approval_mode = "writes"
enabled = true
startup_timeout_sec = 30
tool_timeout_sec = 120

[mcp_servers.overleaf.env]
OVERLEAF_PROJECT_ID = "$EscapedProjectId"
OVERLEAF_GIT_TOKEN_FILE = "$EscapedTokenPath"
"@

Set-Content -Path $ConfigPath -Value $Config -Encoding UTF8

Write-Host ""
Write-Host "Overleaf MCP configured."
Write-Host "Project-scoped Codex config:"
Write-Host "  $ConfigPath"
Write-Host "Token file:"
Write-Host "  $TokenPath"
Write-Host ""
Write-Host "Important:"
Write-Host "  1. Do not commit .codex/config.toml."
Write-Host "  2. Restart Codex / the IDE extension so MCP configuration reloads."
Write-Host "  3. Test with a read-only request first, such as listing Overleaf files."
Write-Host "  4. Write tools should require approval because approval mode is set to 'writes'."
